"use client";

import { useState } from "react";
import type { Incident } from "@/types";
import { Video, FileText, MessageSquare, Check, ChevronDown, ChevronUp } from "lucide-react";

interface Props {
  incident: Incident;
}

export function QuickActions({ incident }: Props) {
  const [toast, setToast] = useState<string | null>(null);
  const [toastType, setToastType] = useState<"success" | "error">("success");
  const [copied, setCopied] = useState(false);
  const [slackUrl, setSlackUrl] = useState(() => {
    if (typeof window !== "undefined") return localStorage.getItem("pulseops_slack_webhook") || "";
    return "";
  });
  const [slackInput, setSlackInput] = useState(slackUrl);
  const [slackConfigOpen, setSlackConfigOpen] = useState(false);
  const [sendingSlack, setSendingSlack] = useState(false);

  const showToast = (msg: string, type: "success" | "error" = "success") => {
    setToast(msg);
    setToastType(type);
    setTimeout(() => setToast(null), 4000);
  };

  const handleZoomBridge = async () => {
    const meetingId = Math.floor(1000000000 + Math.random() * 9000000000);
    const url = `https://zoom.us/j/${meetingId}`;
    try {
      await navigator.clipboard.writeText(url);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      showToast("Zoom bridge link copied to clipboard");
    } catch {
      showToast("Failed to copy — check clipboard permissions", "error");
    }
  };

  const handleExportReport = () => {
    const id = `INC-${String(incident.id).padStart(4, "0")}`;
    const lines = [
      "=".repeat(60),
      `  POST-MORTEM REPORT — ${id}`,
      "=".repeat(60),
      "",
      `Title:       ${incident.title}`,
      `Severity:    ${incident.severity.toUpperCase()}`,
      `Status:      ${incident.status.toUpperCase()}`,
      `Reporter:    ${incident.reporter?.name || "—"}`,
      `Assignee:    ${incident.assignee?.name || "Unassigned"}`,
      `Team:        ${incident.team?.name || "—"}`,
      `Created:     ${new Date(incident.created_at).toLocaleString()}`,
      incident.resolved_at ? `Resolved:    ${new Date(incident.resolved_at).toLocaleString()}` : null,
      "",
      "AFFECTED SERVICES",
      "-".repeat(40),
      ...(incident.services?.map((s) => `  • ${s.name} (${s.status})`) || ["  None"]),
      "",
      "DESCRIPTION",
      "-".repeat(40),
      incident.description || "  No description provided.",
      "",
      "ACTIVITY TIMELINE",
      "-".repeat(40),
      ...(incident.activities?.map((a) => {
        const t = new Date(a.created_at).toLocaleString();
        const user = a.user?.name || "System";
        return `  [${t}] ${user} (${a.type}): ${a.body || ""}`;
      }) || ["  No activity recorded."]),
      "",
      "=".repeat(60),
      `  Generated by PULSE//OPS — ${new Date().toLocaleString()}`,
      "=".repeat(60),
    ];

    const content = lines.filter(Boolean).join("\n");
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${id}-postmortem.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showToast(`Post-mortem report downloaded as ${id}-postmortem.txt`);
  };

  const handleSlackAlert = async () => {
    if (!slackUrl) {
      setSlackConfigOpen(true);
      showToast("Configure your Slack webhook URL first", "error");
      return;
    }

    setSendingSlack(true);
    try {
      const id = `INC-${String(incident.id).padStart(4, "0")}`;
      const severityEmoji = incident.severity === "critical" ? ":red_circle:" : incident.severity === "major" ? ":large_orange_circle:" : ":warning:";
      const payload = {
        blocks: [
          {
            type: "header",
            text: { type: "plain_text", text: `${severityEmoji} ${id}: ${incident.title}` },
          },
          {
            type: "section",
            fields: [
              { type: "mrkdwn", text: `*Severity:*\n${incident.severity.toUpperCase()}` },
              { type: "mrkdwn", text: `*Status:*\n${incident.status.toUpperCase()}` },
              { type: "mrkdwn", text: `*Assignee:*\n${incident.assignee?.name || "Unassigned"}` },
              { type: "mrkdwn", text: `*Team:*\n${incident.team?.name || "—"}` },
            ],
          },
          {
            type: "section",
            text: {
              type: "mrkdwn",
              text: `*Services:* ${incident.services?.map((s) => s.name).join(", ") || "None"}`,
            },
          },
          {
            type: "context",
            elements: [
              { type: "mrkdwn", text: `Sent by PULSE//OPS — ${new Date().toLocaleString()}` },
            ],
          },
        ],
      };

      const res = await fetch(slackUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      if (res.ok || res.status === 200) {
        showToast(`Slack alert sent for ${id}`);
      } else {
        showToast(`Slack webhook returned status ${res.status}`, "error");
      }
    } catch {
      showToast("Failed to send Slack alert — check webhook URL", "error");
    } finally {
      setSendingSlack(false);
    }
  };

  const saveSlackUrl = () => {
    localStorage.setItem("pulseops_slack_webhook", slackInput);
    setSlackUrl(slackInput);
    showToast("Slack webhook URL saved");
  };

  return (
    <div className="rounded border border-border bg-surface p-4">
      <h3 className="mb-3 text-[10px] uppercase tracking-widest text-fg-muted">Quick Actions</h3>
      <div className="space-y-2">
        <button
          onClick={handleZoomBridge}
          className="flex w-full items-center gap-2.5 rounded border border-border bg-canvas px-3 py-2 text-[11px] text-fg-primary transition-colors hover:border-amber/40 hover:bg-hover-row"
        >
          {copied ? <Check className="h-3.5 w-3.5 text-healthy" /> : <Video className="h-3.5 w-3.5 text-amber" />}
          {copied ? "Link Copied!" : "Trigger Zoom Bridge"}
        </button>

        <button
          onClick={handleExportReport}
          className="flex w-full items-center gap-2.5 rounded border border-border bg-canvas px-3 py-2 text-[11px] text-fg-primary transition-colors hover:border-amber/40 hover:bg-hover-row"
        >
          <FileText className="h-3.5 w-3.5 text-amber" />
          Export Post-Mortem Report
        </button>

        <button
          onClick={handleSlackAlert}
          disabled={sendingSlack}
          className="flex w-full items-center gap-2.5 rounded border border-border bg-canvas px-3 py-2 text-[11px] text-fg-primary transition-colors hover:border-amber/40 hover:bg-hover-row disabled:opacity-50"
        >
          <MessageSquare className="h-3.5 w-3.5 text-healthy" />
          {sendingSlack ? "Sending..." : "Generate Slack Alert"}
        </button>
      </div>

      <button
        onClick={() => setSlackConfigOpen(!slackConfigOpen)}
        className="mt-2 flex w-full items-center justify-center gap-1 text-[9px] uppercase tracking-wider text-fg-muted transition-colors hover:text-fg-secondary"
      >
        Slack Webhook {slackUrl ? "\u2713 Configured" : "Not Set"}
        {slackConfigOpen ? <ChevronUp className="h-2.5 w-2.5" /> : <ChevronDown className="h-2.5 w-2.5" />}
      </button>

      {slackConfigOpen && (
        <div className="mt-2 space-y-2">
          <input
            type="url"
            value={slackInput}
            onChange={(e) => setSlackInput(e.target.value)}
            placeholder="https://hooks.slack.com/services/..."
            className="w-full rounded border border-border bg-canvas px-2 py-1.5 font-mono text-[10px] text-fg-primary placeholder-fg-muted/50 outline-none focus:border-amber"
          />
          <button
            onClick={saveSlackUrl}
            className="w-full rounded border border-amber/30 bg-amber/10 px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-amber transition-colors hover:bg-amber/20"
          >
            Save Webhook
          </button>
        </div>
      )}

      {toast && (
        <div
          className={`mt-3 rounded border px-3 py-2 text-[11px] ${
            toastType === "success"
              ? "border-healthy/30 bg-healthy/5 text-healthy"
              : "border-critical/30 bg-critical/5 text-critical"
          }`}
        >
          {toast}
        </div>
      )}
    </div>
  );
}
